# Generated by Django 6.0.4 on 2026-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=10, unique=True)),
                ('text', models.TextField()),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
            ],
        ),
    ]
