# Generated by Django 6.0.4 on 2026-05-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('responses', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
