# Generated by Django 6.0.4 on 2026-05-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_item_response_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
